# Script deletion configuration
script_deletion:
  create_carcases.py: true
  create_simple_items.py: true
  make_recipe_advancements.py: true
  create_entity_tables.py: true
  loot_table_generator.py: true
